---

- name: Install Zabbix agent
  hosts: "{{ host }}"
  tasks:
  
    - name: Download zabbix repo package
      get_url:
        url: "https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb"
        dest: /tmp/zabbix.deb
    
    - name: Install zabbix repo
      become: yes
      apt:
        deb: /tmp/zabbix.deb
        state: present

    - name: Install zabbix agent
      become: yes
      apt:
        name: 
            - zabbix-agent2
            - zabbix-agent2-plugin-*
        state: present
        update_cache: yes

    - name: Stop service zabbix-agent
      become: yes
      service:
        name: zabbix-agent2
        state: stopped

    - name: Remove zabbix config file
      become: yes
      file:
        path: /etc/zabbix/zabbix_agent2.conf
        state: absent

    - name: Create new zabbix config file from template
      become: yes
      template:
        src: "zabbix_agent2.conf"
        dest: "/etc/zabbix/zabbix_agent2.conf"

    - name: Start service zabbix-agent
      become: yes
      service:
        name: zabbix-agent2
        state: started
        enabled: yes